# Generated by Django 4.2.6 on 2023-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('website', models.TextField()),
                ('location', models.TextField()),
                ('min_project_size', models.TextField()),
                ('hourly_rate', models.TextField()),
                ('employee_size', models.TextField()),
                ('linkedin_url', models.TextField()),
            ],
        ),
    ]
