# Generated by Django 4.2.6 on 2023-11-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clutch_company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.TextField()),
                ('client_company', models.TextField()),
                ('position', models.TextField()),
                ('industry', models.TextField()),
                ('employee_size', models.TextField()),
                ('location', models.TextField()),
                ('review_for', models.TextField()),
                ('review', models.TextField()),
                ('review_date', models.TextField()),
                ('project_category', models.TextField()),
                ('project_budgets', models.TextField()),
                ('project_duration', models.TextField()),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_review', to='clutch_company.company')),
            ],
        ),
    ]
