# Generated by Django 4.2.7 on 2023-11-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clutch_company', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='position',
            field=models.TextField(default=None),
        ),
    ]
